# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ### COMPILE PROJECT ###
  compile:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile Pacman Project and Tests
        working-directory: Projects/P1
        run: javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java
        

  ### TESTS ###
  TestPacManMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test PacMan Move
        working-directory: Projects/P1
        run: |
          javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java 
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
          
  TestGhostMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Ghost Move
        working-directory: Projects/P1
        run: |
          javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java 
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
          
  TestMapAttack:
     runs-on: ubuntu-latest
     container: openjdk
     steps:
      - uses: actions/checkout@v2
      - name: Test Map Attack
        working-directory: Projects/P1
        run: |
          javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java 
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapAttack



  TestPacManValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test PacMan Valid Moves
        working-directory: Projects/P1
        run: |
          javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java 
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves

  TestGhostValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Ghost Valid Moves
        working-directory: Projects/P1
        run: |
          javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java 
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves
  
  TestMapMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test Map Move
        working-directory: Projects/P1
        run: |
          javac -cp "tests/junit-4.10.jar:." src/*.java tests/*.java 
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove
      
